version: '3.8'

services:
  todo-app:
    build: .
    ports:
      - "${TODO_PORT}:${TODO_PORT}" 
    environment:
      TODO_PASSWORD: ${TODO_PASSWORD:-12345}
      TODO_DBFILE: /app/scheduler.db
      TODO_PORT: ${TODO_PORT:-7540}
    volumes:
      - ./scheduler.db:/app/scheduler.db